// Realistic reply threads for seed posts - based on WCI forum patterns, Reddit r/whitecoatinvestor, physician finance discussions
export const SEED_REPLIES = {
  1: [
    {id:1001,body:"Made this exact switch 3 years ago. $380K academic to $670K private. Zero regrets financially but I genuinely miss the residents. If teaching matters to you, some private groups let you take students 1-2 days/week. Ask about it.",specialty:"Cardiology",time:"1h ago",upvotes:67},
    {id:1002,body:"Run the numbers on total comp, not just base. Academic usually has better retirement match (sometimes 10%+), paid CME, sabbatical, and lower malpractice. My 'lower' academic salary is really only $80K less when you add everything up.",specialty:"Internal Medicine",time:"2h ago",upvotes:43},
    {id:1003,body:"$55/wRVU above 7500 is decent but make sure you understand the collection rate. If they're collecting 85% vs 95% that changes your real $/wRVU significantly. Get 3 years of wRVU data from the practice before signing.",specialty:"Cardiology",time:"3h ago",upvotes:38},
    {id:1004,body:"I left academic for private 5 years ago. Income tripled. But I'm now trapped by the golden handcuffs and a 2-year non-compete. The money is great but I lost something intangible. Just go in with eyes open.",specialty:"Gastroenterology",time:"5h ago",upvotes:29},
    {id:1005,body:"Heavy call in private cards is no joke. Ask exactly what 'heavy call' means: how many weekends/month, STEMI activation frequency, how many partners share call. I did q3 call for 2 years and nearly burned out.",specialty:"Cardiology",time:"8h ago",upvotes:52},
  ],
  3: [
    {id:1006,body:"How are you handling prescribing across state lines? I want to do this but licensing in multiple states is expensive and time-consuming. IMLC helped but not all states participate.",specialty:"Psychiatry",time:"2h ago",upvotes:34},
    {id:1007,body:"$350/hr cash pay is great but you're leaving money on the table if you're not also doing med management follow-ups at $200-250 for 15-min visits. That's $800-1000/hr effective rate. Mix therapy and med management patients.",specialty:"Psychiatry",time:"4h ago",upvotes:51},
    {id:1008,body:"What platform do you use? I've been debating between SimplePractice and my own Stripe + Calendly setup. The platforms take 3-5% which adds up fast at your volumes.",specialty:"Psychiatry",time:"6h ago",upvotes:22},
    {id:1009,body:"Be careful with this model long-term. Cash-pay psych works now because demand massively exceeds supply. If AI therapy tools or mid-levels erode demand, that $350/hr rate could compress. Diversify.",specialty:"Family Medicine",time:"1d ago",upvotes:15},
  ],
  5: [
    {id:1010,body:"22 patients per shift is unsafe. AMA guidelines suggest 15-18 for inpatient medicine. Document your concerns in writing to your CMO. If something goes wrong, you want a paper trail showing you raised safety concerns.",specialty:"Internal Medicine",time:"1h ago",upvotes:78},
    {id:1011,body:"Nocturnist premium is the move. I switched to nights only at $370K for 7on/7off. Fewer patients (12-15), less admin interference, and a 20% pay bump. Sleep schedule is rough but I adjusted after 3 months.",specialty:"Internal Medicine",time:"3h ago",upvotes:45},
    {id:1012,body:"Locums hospitalist rates are $180-220/hr depending on region. That's $375-460K annualized with way more schedule flexibility. No benefits but you can buy your own for $15K/yr and still come out ahead.",specialty:"Internal Medicine",time:"5h ago",upvotes:33},
    {id:1013,body:"Same here. Our group went from 16 to 24 average census per doc over 4 years. Admin hired 2 APPs instead of 2 physicians because it's cheaper. Now I'm supervising APPs AND seeing my own full panel. Worse for everyone.",specialty:"Internal Medicine",time:"1d ago",upvotes:61},
  ],
  14: [
    {id:1014,body:"Peds hospitalist here. $235K with $310K in loans. My resident friends in tech are clearing $200K with zero debt and 4 years head start. The opportunity cost of medical training is $2-3M when you actually model it out.",specialty:"Pediatrics",time:"1h ago",upvotes:89},
    {id:1015,body:"PSLF is the only way peds math works. 10 years of IBR payments then forgiveness. My projected forgiveness is $280K tax-free. Without PSLF I'd be paying loans until I'm 50.",specialty:"Pediatrics",time:"3h ago",upvotes:56},
    {id:1016,body:"Subspecialize. Peds cardiology: $350K. Peds GI: $340K. Peds critical care: $330K. General peds is the worst paid but subspecialties are competitive. The extra 3 years of fellowship is worth it financially.",specialty:"Pediatrics",time:"6h ago",upvotes:41},
    {id:1017,body:"Controversial take: peds compensation will only improve when fewer people apply. As long as it's a competitive residency, hospitals have no incentive to pay more. Supply and demand.",specialty:"Emergency Medicine",time:"1d ago",upvotes:34},
    {id:1018,body:"I left peds for urgent care after 5 years. Income went from $225K to $310K. I miss the kids but I don't miss being unable to afford a house in the city where I work. Financial stress was affecting my patient care.",specialty:"Pediatrics",time:"1d ago",upvotes:47},
  ],
  21: [
    {id:1019,body:"Non-competes vary HUGELY by state. Some states (CA, CO, OK, ND) ban them entirely for physicians. Others enforce them strictly. Before signing, spend the $500 to have a healthcare attorney review it. Best money I ever spent.",specialty:"Orthopedic Surgery",time:"2h ago",upvotes:72},
    {id:1020,body:"I negotiated my non-compete from 25 miles/2 years down to 10 miles/1 year before signing. They pushed back but ultimately agreed because they wanted me. You have the most leverage before you sign. Use it.",specialty:"Cardiology",time:"4h ago",upvotes:53},
    {id:1021,body:"Had a similar situation. My attorney found that the non-compete was overly broad and likely unenforceable in our state. Sent a demand letter. They settled for a $50K buyout instead of litigation. Sometimes the threat is enough.",specialty:"Dermatology",time:"8h ago",upvotes:38},
    {id:1022,body:"Pro tip: even in states that enforce non-competes, they often don't apply if you're terminated without cause. Read the termination clause carefully. Mine only applies if I voluntarily resign.",specialty:"Gastroenterology",time:"1d ago",upvotes:44},
  ],
  22: [
    {id:1023,body:"$85K for tail is actually on the lower end for surgery. My colleague got quoted $120K. Rule of thumb: tail coverage costs 1.5-2x your annual malpractice premium. ALWAYS negotiate this before signing.",specialty:"General Surgery",time:"1h ago",upvotes:81},
    {id:1024,body:"Better yet: negotiate for occurrence-based malpractice instead of claims-made. Occurrence policies don't need tail coverage at all. Costs the employer more upfront but saves you $100K+ when you leave.",specialty:"Orthopedic Surgery",time:"3h ago",upvotes:67},
    {id:1025,body:"My contract says employer pays tail if I'm terminated without cause, I pay if I leave voluntarily. Seems fair. But get it explicitly in writing, not a verbal promise from the CMO who might not be there when you leave.",specialty:"Internal Medicine",time:"6h ago",upvotes:53},
    {id:1026,body:"Lost a partner over this exact issue. He left our group, discovered he owed $95K in tail, couldn't afford it, and practiced uncovered for 3 months. Terrifying. Now we include tail in all our partnership agreements.",specialty:"Gastroenterology",time:"1d ago",upvotes:39},
    {id:1027,body:"Also worth knowing: some states require the employer to provide tail if they terminate you. Check your state medical board regulations, not just your contract.",specialty:"Radiology",time:"1d ago",upvotes:28},
  ],
  37: [
    {id:1028,body:"This is literally the WCI playbook and it works. I'm on the same path: $360K income, $80K spend, all excess into VTI/VXUS/BND. Net worth crossed $1.5M at 40. On track for $3M by 45. The math is simple, the discipline is hard.",specialty:"Anesthesiology",time:"30m ago",upvotes:73},
    {id:1029,body:"Living like a resident is easy to say, hard to do when your co-attendings are buying $1.2M houses and new Teslas. My spouse and I set a 3-year 'resident lifestyle' pact before I started attending life. Having a defined end date made it bearable.",specialty:"Emergency Medicine",time:"2h ago",upvotes:58},
    {id:1030,body:"Counterpoint: I 'lived like a resident' for 5 years and burned out from the deprivation. Now I spend $150K/yr, still save 45% of gross, and I'm much happier. Find your personal balance. FIRE isn't the only path.",specialty:"Dermatology",time:"5h ago",upvotes:45},
    {id:1031,body:"What's your asset allocation? Curious if you're 100% equities or have a bond tent. Also, at $2M and 42, you're technically FI but are you actually retiring or coastFIRE?",specialty:"Radiology",time:"8h ago",upvotes:22},
    {id:1032,body:"Don't forget sequence of returns risk. $2M at 42 with a 4% withdrawal rate ($80K) might not survive a bad first-5-years bear market. I'd want $2.5-3M minimum before pulling the plug at 42. Or at least keep a part-time gig.",specialty:"Neurology",time:"1d ago",upvotes:37},
  ],
  42: [
    {id:1033,body:"Northwestern Mutual rep nearly got me too. They show these beautiful illustrations projecting 6-7% returns. Reality: average whole life dividend rates are 4-5% ON THE CASH VALUE, which takes 10-15 years to equal your premiums. Net return is like 2%.",specialty:"Orthopedic Surgery",time:"1h ago",upvotes:82},
    {id:1034,body:"BTID (buy term invest difference) wins 95% of the time. 20-year term for a healthy 30-year-old physician is like $50/month for $2M coverage. Put the $700/month premium difference into index funds and you'll have $500K+ in 20 years.",specialty:"Internal Medicine",time:"3h ago",upvotes:63},
    {id:1035,body:"Unpopular opinion: whole life has a narrow use case for physicians with $5M+ net worth doing estate planning. The death benefit passes tax-free and can fund an ILIT to pay estate taxes. For everyone else, BTID wins.",specialty:"Cardiology",time:"6h ago",upvotes:31},
    {id:1036,body:"The NWM rep who pitched me was a former classmate from college. Made it SO awkward to say no. But I did the math and the opportunity cost over 30 years was $1.2M. Friendship didn't survive either way.",specialty:"Family Medicine",time:"1d ago",upvotes:48},
  ],
  45: [
    {id:1037,body:"This is why own-occ is non-negotiable for proceduralists. Surgeons, cardiologists, GI docs - if you can't do procedures, any-occ DI would say 'but you can still see patients in clinic.' Own-occ covers you for YOUR specialty.",specialty:"General Surgery",time:"1h ago",upvotes:71},
    {id:1038,body:"Get DI while you're in residency. Premiums are 30-40% cheaper and you lock in a lower rate for life. I pay $180/month for $12K/month benefit with own-occ and future increase riders. My attending friends pay $350+ for the same coverage.",specialty:"Anesthesiology",time:"4h ago",upvotes:55},
    {id:1039,body:"Also important: make sure your policy is non-cancellable AND guaranteed renewable. Some policies are only guaranteed renewable, which means they can raise premiums on your entire risk class. Non-cancellable locks your rate.",specialty:"Radiology",time:"7h ago",upvotes:42},
    {id:1040,body:"$15K/month benefit for 8 months = $120K. That's the difference between financial stress and stability during recovery. DI is the one insurance product every physician should have. Period.",specialty:"Orthopedic Surgery",time:"1d ago",upvotes:38},
  ],
  49: [
    {id:1041,body:"Congrats! I'm at payment 87 of 120. The anxiety of trusting the government to follow through is real. I keep meticulous records: every payment receipt, every ECF, every employer certification. Redundant backups on cloud and local.",specialty:"Internal Medicine",time:"30m ago",upvotes:64},
    {id:1042,body:"Key insight: $180K paid over 10 years on IBR vs $340K forgiven means you paid $0.53 per dollar of original debt. And those IBR payments were partially tax-deductible. Effective cost was even lower. PSLF is mathematically incredible for high-debt physicians.",specialty:"Pediatrics",time:"2h ago",upvotes:51},
    {id:1043,body:"Did you have any payments that didn't qualify initially? I had 14 months of payments rejected because my servicer put me on the wrong plan. Took 8 months of appeals to fix. MOHELA is a nightmare to deal with.",specialty:"Family Medicine",time:"5h ago",upvotes:37},
    {id:1044,body:"For anyone reading: SAVE plan changes in 2025 complicated things. Make sure you're on the right IDR plan for PSLF. Some plans qualify, others don't. Check studentaid.gov regularly and recertify income annually.",specialty:"Psychiatry",time:"1d ago",upvotes:29},
    {id:1045,body:"PSLF is why I chose academic over private. Private offered $100K more per year but after PSLF forgiveness, the 10-year total comp is nearly identical. And I got research time, teaching, and a slower pace.",specialty:"Neurology",time:"1d ago",upvotes:43},
  ],
  51: [
    {id:1046,body:"Fire your advisor. Three-fund portfolio (US total market + international + bonds) through Vanguard or Fidelity costs 0.03-0.10% in expense ratios. You'll save $14K/yr and probably get better returns because 80% of active managers underperform the index.",specialty:"Radiology",time:"30m ago",upvotes:76},
    {id:1047,body:"Counter-argument: a good advisor does more than pick investments. Tax-loss harvesting, Roth conversion strategy, estate planning coordination, insurance review, behavioral coaching during crashes. Some earn their 1%. Most don't.",specialty:"Cardiology",time:"3h ago",upvotes:42},
    {id:1048,body:"Switched from a 1% AUM advisor to a flat-fee financial planner ($3K/year for comprehensive planning). Get the same advice without the asset drain. At $1.5M, the 1% drag costs you $400K+ over 20 years after compounding.",specialty:"Anesthesiology",time:"6h ago",upvotes:55},
    {id:1049,body:"I use Vanguard Personal Advisor for 0.30% on my $2M portfolio. That's $6K/yr vs $20K/yr at 1%. Includes a human advisor, tax planning, and rebalancing. Best middle ground I've found.",specialty:"Dermatology",time:"1d ago",upvotes:33},
  ],
  56: [
    {id:1050,body:"Did the same thing. 0.8 FTE, lost $65K but my blood pressure dropped 20 points, stopped the Lexapro, and actually enjoy medicine again. The ROI on health is infinite. Your future self will thank you.",specialty:"Internal Medicine",time:"1h ago",upvotes:62},
    {id:1051,body:"The math people miss: at a 37% marginal tax rate, a $90K pay cut only costs you $57K after taxes. And if you were spending $15K/year on stress-related expenses (alcohol, takeout, therapy, medical bills), the real cost is $42K. Totally worth it.",specialty:"Psychiatry",time:"3h ago",upvotes:54},
    {id:1052,body:"I wish I'd done this before my divorce. I was making $480K working full-time and spending none of it with my family. Now I'm making $380K part-time and actually present for my kids. Don't wait until it's too late.",specialty:"Orthopedic Surgery",time:"7h ago",upvotes:71},
    {id:1053,body:"How did you approach the conversation with your group? I want to go part-time but worried they'll see me as 'not committed' and I'll miss partnership track.",specialty:"Gastroenterology",time:"1d ago",upvotes:18},
  ],
  57: [
    {id:1054,body:"Thank you for sharing this. It takes courage. I had a similar experience - missed a subdural on a head CT because I was post-call and my pattern recognition was shot. Nobody talks about how fatigue degrades clinical judgment. It should be a systems issue, not a personal failure.",specialty:"Radiology",time:"1h ago",upvotes:83},
    {id:1055,body:"This is why duty hour restrictions matter. I know the 'back in my day we worked 120 hours' crowd hates it, but sleep-deprived physicians make more errors. Full stop. The data is unambiguous.",specialty:"Emergency Medicine",time:"4h ago",upvotes:67},
    {id:1056,body:"Three errors in a month is a system screaming at you, not a character flaw. Glad you took the break. For anyone reading: most hospitals have confidential physician support programs. Use them before you reach crisis.",specialty:"Psychiatry",time:"8h ago",upvotes:49},
    {id:1057,body:"I reported myself to our patient safety team after a near-miss. Terrifying decision but the right one. They identified systemic issues (understaffing, inadequate handoff protocols) that were affecting everyone. Sometimes the bravest thing is speaking up.",specialty:"Internal Medicine",time:"1d ago",upvotes:55},
  ],
  59: [
    {id:1058,body:"You're not alone. Medscape 2025 survey: 44% of psychiatrists report burnout symptoms, higher than the physician average. We absorb everyone's trauma while pretending we're immune. Please keep getting help.",specialty:"Psychiatry",time:"30m ago",upvotes:89},
    {id:1059,body:"It took me 3 years to recognize my own depression. I was diagnosing it daily in patients but couldn't see it in the mirror. The physician heal thyself mentality is toxic. Medication + therapy changed everything.",specialty:"Psychiatry",time:"2h ago",upvotes:73},
    {id:1060,body:"Anesthesiologist here. We have the highest rates of substance use disorder and suicide among specialties. The culture of invincibility in medicine needs to die. Your post will help someone. Thank you.",specialty:"Anesthesiology",time:"5h ago",upvotes:61},
    {id:1061,body:"For anyone struggling: the Dr. Lorna Breen Heroes Foundation (drlornabreen.org) has resources specifically for physician mental health. Most state PHPs are confidential and won't report to your medical board for seeking treatment.",specialty:"Family Medicine",time:"1d ago",upvotes:47},
    {id:1062,body:"I'm an IM attending who went through this. Got help, went on sertraline, and the fog lifted within 6 weeks. Best decision of my life. Your patients need you healthy first.",specialty:"Internal Medicine",time:"1d ago",upvotes:52},
  ],
  60: [
    {id:1063,body:"80-120 messages per day is medical practice without compensation. AMA formally recognized this as unpaid labor in 2024. Start tracking your time and present it to admin. In our group, we negotiated 2 hours of protected inbox time per day, paid.",specialty:"Family Medicine",time:"1h ago",upvotes:74},
    {id:1064,body:"I set a hard boundary: portal messages get 48-hour response time. Complex questions get 'Please schedule an appointment to discuss this.' My inbox dropped 40% overnight. Patients adjusted.",specialty:"Internal Medicine",time:"3h ago",upvotes:59},
    {id:1065,body:"Epic's InBasket is the worst-designed clinical tool in healthcare. Every lab result, every imaging report, every referral letter, every pharmacy request - all dumped into the same inbox. Zero triage, zero prioritization. A CS intern could design something better.",specialty:"Family Medicine",time:"6h ago",upvotes:66},
    {id:1066,body:"Our hospital implemented AI-assisted triage for inbox messages. Sorts them into urgent/routine/informational. Urgent gets flagged immediately, routine batched for end-of-day review. Cut my inbox time by 50%.",specialty:"Internal Medicine",time:"1d ago",upvotes:41},
  ],
  75: [
    {id:1067,body:"$4.5M at 52 with a 3.5% withdrawal rate = $157K/yr. Add Social Security at 67 and you're looking at $200K+ per year forever. Well done. The Camry detail is perfect - car payments are where physician wealth goes to die.",specialty:"Internal Medicine",time:"30m ago",upvotes:71},
    {id:1068,body:"35% savings rate on $380K starting salary means $133K/yr invested from day one. That's aggressive but absolutely the right move. The first 10 years of compound growth matter most. People who wait until 40 to start saving aggressively can never catch up.",specialty:"Radiology",time:"2h ago",upvotes:54},
    {id:1069,body:"What's your healthcare plan for the gap between retirement and Medicare at 65? ACA marketplace premiums for a 52-year-old couple can be $1,500-2,000/month. That's a meaningful expense for 13 years.",specialty:"Family Medicine",time:"5h ago",upvotes:38},
    {id:1070,body:"Congratulations. I'm on a similar path but retiring at 55. The key nobody talks about: Roth conversion ladder. Convert traditional IRA to Roth each year in early retirement when your income is low. Pay 12-22% tax now instead of 35%+ later.",specialty:"Anesthesiology",time:"1d ago",upvotes:46},
    {id:1071,body:"What does your spouse think about retiring at 52? My wife is fully on board but I've seen several WCI forum posts where the non-physician spouse freaks out about leaving 'guaranteed income.' Alignment matters more than the numbers.",specialty:"Cardiology",time:"1d ago",upvotes:33},
  ],
  82: [
    {id:1072,body:"ASC ownership is the single greatest wealth-building tool in procedural medicine. Our 6-doc GI group owns 2 ASCs. Average partner income: $850K professional + $400K ASC distributions. Total comp over $1.2M. The equity is worth $3-4M per partner.",specialty:"Gastroenterology",time:"1h ago",upvotes:65},
    {id:1073,body:"Hospital systems are acquiring ASCs aggressively right now, paying 8-12x EBITDA. If your ASC generates $500K EBITDA per partner, that's a $4-6M buyout. Some of my GI colleagues retired in their 40s from ASC sales alone.",specialty:"Gastroenterology",time:"4h ago",upvotes:48},
    {id:1074,body:"Ortho here. We have an ASC for scopes and joint injections. The key is owning the facility fee AND the professional fee. If you're just doing professional services at someone else's ASC, you're leaving 60% on the table.",specialty:"Orthopedic Surgery",time:"7h ago",upvotes:37},
    {id:1075,body:"Important caveat: Stark Law and Anti-Kickback regulations are complex with ASC ownership. Make sure you have a healthcare attorney structure the entity properly. One compliance violation can shut the whole thing down.",specialty:"Cardiology",time:"1d ago",upvotes:29},
  ],
  86: [
    {id:1076,body:"Same story at our shop. Independent group for 18 years, hospital sold to a CMG, half the group quit within 12 months. The new company's idea of 'efficiency' was cutting support staff and increasing volume expectations by 30%.",specialty:"Emergency Medicine",time:"1h ago",upvotes:78},
    {id:1077,body:"This is happening everywhere in EM. TeamHealth, Envision, SCP - the large CMGs are acquiring contracts and then cutting costs (your pay) to maximize margins. The democratic group model is dying and it's tragic for patient care.",specialty:"Emergency Medicine",time:"3h ago",upvotes:64},
    {id:1078,body:"I left when the CMG took over. Went to a freestanding ED run by an independent group. Pay is slightly less but I have a voice in scheduling, staffing, and clinical protocols again. Autonomy is worth $30-40K to me.",specialty:"Emergency Medicine",time:"6h ago",upvotes:51},
    {id:1079,body:"The ACEP has been raising alarm bells about CMG consolidation since 2020. If your group's contract is up for renewal, start building relationships with hospital admin NOW. It's harder to replace an existing group that admin likes.",specialty:"Emergency Medicine",time:"1d ago",upvotes:35},
  ],
  90: [
    {id:1080,body:"PE playbook is always the same: acquire, optimize (cut costs), leverage (add debt), flip in 3-5 years. 'Optimize' means replace physicians with CRNAs/APPs, reduce benefits, increase volume. You're not a partner, you're a cost center.",specialty:"Anesthesiology",time:"1h ago",upvotes:82},
    {id:1081,body:"Was in the exact same situation. Our 25-doc group sold to PE. Year 1 was fine (honeymoon period). Year 2 they brought in CRNAs for 50% of cases. Year 3 they cut the partnership distribution by 40%. Year 4 I left.",specialty:"Anesthesiology",time:"4h ago",upvotes:67},
    {id:1082,body:"If your group is considering a PE sale, demand: guaranteed employment terms for 3+ years, no-cut clauses on compensation, golden parachute if you're pushed out. Most PE firms won't agree to all three. That tells you everything.",specialty:"Dermatology",time:"8h ago",upvotes:43},
    {id:1083,body:"The upfront buyout checks are tempting. Our partners each got $800K at close. But we gave up $200K/yr in income for the next 5+ years. Net negative by year 5. PE wins, physicians lose. Every. Single. Time.",specialty:"Anesthesiology",time:"1d ago",upvotes:56},
    {id:1084,body:"Not all PE deals are bad. Our ophthalmology group sold to PE 4 years ago. They invested in new equipment, expanded locations, and my income went UP 25%. Key: pick a PE firm that invests in growth, not just cost-cutting.",specialty:"Ophthalmology",time:"1d ago",upvotes:21},
  ],
  99: [
    {id:1085,body:"Peds subspecialist at a children's hospital. $195K after 3 years of fellowship + 2 years of attending. My roommate from college works in marketing and makes more. I love my patients but I can barely afford daycare for my own kids.",specialty:"Pediatrics",time:"1h ago",upvotes:75},
    {id:1086,body:"The culture is what keeps us. I've had offers for $80K more at adult hospitals but the team at my children's hospital is family. Sometimes the non-financial compensation (colleagues, mission, environment) is worth the pay gap. Sometimes.",specialty:"Pediatrics",time:"3h ago",upvotes:48},
    {id:1087,body:"Children's hospitals can afford to pay less because there's never a shortage of applicants. It's the cruelest irony in medicine: the most altruistic physicians get paid the least because their motivation can be exploited.",specialty:"Emergency Medicine",time:"6h ago",upvotes:62},
    {id:1088,body:"PSLF is the only way to make children's hospital math work. 10 years of income-driven payments then $300K+ forgiven tax-free. Without PSLF I'd have left 5 years ago. Plan accordingly and document EVERYTHING.",specialty:"Pediatrics",time:"1d ago",upvotes:41},
    {id:1089,body:"Moonlighting is key if your hospital allows it. I do 2 urgent care shifts per month at $150/hr. Extra $30K/yr makes a meaningful difference when your base is $210K. Check your contract for moonlighting clauses.",specialty:"Pediatrics",time:"1d ago",upvotes:33},
  ],
};
